"""reprogramacion pendiente para

Revision ID: 010c97cecd00
Revises: 26149302cef7
Create Date: 2025-08-26 19:46:52.223830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010c97cecd00'
down_revision = '26149302cef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reprog_pendiente_para', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('reprog_pendiente_para')

    # ### end Alembic commands ###
