"""Nuevas columnas para usuarios

Revision ID: 0f9f82d4502f
Revises: 9ebb7c01a763
Create Date: 2025-09-04 18:27:16.422078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f9f82d4502f'
down_revision = '9ebb7c01a763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salidas_vivienda', schema=None) as batch_op:
        batch_op.alter_column('fecha_salida',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('fecha_regreso',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=10), server_default='activo', nullable=False))
        batch_op.add_column(sa.Column('residencia', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pabellon', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('habitacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index(batch_op.f('ix_usuarios_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_fecha_registro'), ['fecha_registro'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_fecha_registro'))
        batch_op.drop_index(batch_op.f('ix_usuarios_estado'))
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('habitacion')
        batch_op.drop_column('pabellon')
        batch_op.drop_column('residencia')
        batch_op.drop_column('estado')

    with op.batch_alter_table('salidas_vivienda', schema=None) as batch_op:
        batch_op.alter_column('fecha_regreso',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('fecha_salida',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###
