"""Agregando columnas al modulo de Cita

Revision ID: 26149302cef7
Revises: 1102fff7bdce
Create Date: 2025-08-25 18:33:04.421786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26149302cef7'
down_revision = '1102fff7bdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reprog_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reprog_horario', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reprog_solicitada_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reprog_estado', sa.String(length=20), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_unique_constraint('uq_citas_area_fecha_horario', ['area', 'fecha', 'horario'])
        batch_op.create_foreign_key(None, 'usuarios', ['reprog_solicitada_por'], ['id_usuario'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('usuarios_correo_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))
        batch_op.create_unique_constraint(batch_op.f('usuarios_correo_key'), ['correo'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_citas_area_fecha_horario', type_='unique')
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('reprog_estado')
        batch_op.drop_column('reprog_solicitada_por')
        batch_op.drop_column('reprog_horario')
        batch_op.drop_column('reprog_fecha')

    # ### end Alembic commands ###
