"""nuevas tablas area y motivo

Revision ID: 5edb9ca7eda7
Revises: 0f9f82d4502f
Create Date: 2025-09-10 15:06:55.814504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edb9ca7eda7'
down_revision = '0f9f82d4502f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_area'),
    sa.UniqueConstraint('area')
    )
    op.create_table('motivo_cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=120), nullable=False),
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_area'], ['areas.id_area'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('motivo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motivo_cita')
    op.drop_table('areas')
    # ### end Alembic commands ###
