"""nuevas columnas citas

Revision ID: 9ebb7c01a763
Revises: 010c97cecd00
Create Date: 2025-08-26 23:02:08.664671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebb7c01a763'
down_revision = '010c97cecd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reprog_motivo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reprog_evid_bucket', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reprog_evid_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('reprog_evid_name')
        batch_op.drop_column('reprog_evid_bucket')
        batch_op.drop_column('reprog_motivo')

    # ### end Alembic commands ###
