"""Add motivo_cancelacion to actividades

Revision ID: e4e60344b53a
Revises: e3d31ca3598a
Create Date: 2025-08-15 15:46:43.939876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e60344b53a'
down_revision = 'e3d31ca3598a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_cancelacion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_column('motivo_cancelacion')

    # ### end Alembic commands ###
